// Couleurs par genre
export const genreColors = {
  Action: "bg-red-500",
  Comédie: "bg-yellow-500",
  Drame: "bg-blue-500",
  "Science-Fiction": "bg-purple-500",
  "Science Fiction": "bg-purple-500",
  Horreur: "bg-orange-500",
  Thriller: "bg-gray-500",
  Animation: "bg-green-500",
  Aventure: "bg-teal-500",
  Adventure: "bg-teal-500",
  Fantastique: "bg-pink-500",
  Fantasy: "bg-purple-500",
  Documentaire: "bg-cyan-500",
  Romance: "bg-rose-500",
  Guerre: "bg-indigo-500",
  Musical: "bg-lime-500",
  Policier: "bg-amber-500",
  Biographie: "bg-sky-500",
  Famille: "bg-violet-500",
  Comics: "bg-fuchsia-500",
  Western: "bg-stone-500",
  Sport: "bg-gray-700",
  Historique: "bg-zinc-500",
  Espionnage: "bg-blueGray-500",
  Crime: "bg-emerald-500",
};
